version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URI=postgres://localhost:5431/tasks?user=postgres&password=postgres&sslmode=disable
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres
    #networks:
    #  - host
    network_mode: "host"


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
      - DATABASE_HOST=localhost:5432
      - PGPORT=5431
    ports:
      - 5431:5431
    volumes:
      - database_postgres:/var/lib/postgresql/data
    network_mode: "host"

  migrations:
    image: migrate/migrate
    network_mode: "host"
    environment:
      - POSTGRES_URI=postgres://localhost:5431/tasks?user=postgres&password=postgres&sslmode=disable
    volumes:
      - ${PWD}/migrations:/migrations
    command: ["-verbose", "-path", "migrations", "-database",  $POSTGRES_URI, "up"]

    depends_on:
      - fullstack-postgres

volumes:
  #mmm:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
#networks:
#  host:
#    driver: host